### PR TITLE
Remove clean and set brightness from begin

### PR DESCRIPTION
**Pull request by smaryus**
Remove clean and set brightness from begin method  because on ESP8266 when resuming from deep sleep would create flickering. This is because ESP8266 when it wakes up from deep sleep the device does a restart, which would invoke begin().

### CODE REVIEW

**Comment by jasonacox** [comment]
I would like to test this on the Arduino Uno and an ATtiny to make sure we don't have unintended side effects.

Thanks for submitting this!

**Comment by smaryus** [comment]
Sure, thanks for checking it. 
if you want not to change the current behavior of the library, then maybe you can change the PR and have a parameter for `begin` to control the clean and it is true by default?

**Comment by jasonacox** [comment]
> change the PR and have a parameter for begin to control the clean and it is true by default

This is brilliant!  I like this!

**Comment by jasonacox** [comment]
Thanks @smaryus !

**Pull request merged**
